### PR TITLE
Express checkout

### PR DESCRIPTION
**Pull request by aldeed**
@aaronjudd I think this is essentially done and working, but I'm running into some workflow state issue on what should be the final redirect. "event paymentMethod inappropriate in current state addAddress"

You can probably figure out a solution faster than I can.

Here's the gist of this development:

* Uses the new [in-context checkout flow](https://developer.paypal.com/docs/classic/express-checkout/in-context/)
* You need merchantId in addition to the API credentials (added this to schema/settings form). Merchant ID is on the left side when you log into regular paypal and click the settings gear icon.
* When testing, you log into the checkout popup with the "buyer" sandbox account user/pass

This PR also adjusts the code/file organization.

To do:

* Figure out why calling `CartWorkflow.paymentMethod` at the end of the flow in routing.coffee isn't working.
* Check that I'm user proper values in the object I'm passing to `paymentMethod`. It's a bit different from payFlow (no card details, etc.)
* I didn't test in live mode, but that's probably a good idea once working consistently in sandbox mode.

### CODE REVIEW

**Comment by aldeed** [comment]
In general I was following this, but had to make a few modifications, plus in-context checkout is slightly different (does more of it for you): https://developer.paypal.com/docs/classic/express-checkout/ht_ec-singleAuthPayment-curl-etc/

**Comment by aaronjudd** [comment]
reset project, testing local, after hunting down the credentials (and adding to private/settings/reaction.json) I'm getting this error:

>Exception from Tracker afterFlush function:
debug.js:41 TypeError: Cannot read property 'checkout_tag' of undefined
    at b.exports (button.js:10)
    at b.exports (button.js:11)
    at Object.e.create (button.js:11)
    at _addButtonElement (checkout.js:792)
    at _initWithButtonGeneration (checkout.js:841)
    at Object.paypal.checkout.app.setup (checkout.js:884)
    at doSetup (checkoutButton.coffee:10)
    at Template.paypalCheckoutButton.rendered (checkoutButton.coffee:37)
    at runTemplateHooks (template-extension.js:375)
    at templateExtensionMasterHook (template-extension.js:324)

**Comment by aaronjudd** [comment]
With the updates I've just committed, (added back paypal-rest-sdk) I'm able to checkout through the entire flow with both methods.

However, with express checkout I received this (as the order confirmation page loaded):
>ACK Failure: A successful transaction has already been completed for this token

**Comment by aaronjudd** [comment]
This is now working well, but there a few edge case problems.  Need to fix locale, and check how paypal is converting currency as the numbers aren't matching: see: https://github.com/reactioncommerce/reaction/issues/366

There (might) be some issues with checkout on multiple devices / sessions with the actual paypal button/token.

Popup / modal might not work in mobile.

**Comment by aldeed** [comment]
@aaronjudd, their express checkout lib is specifically designed to work on mobile. On tablet/mobile, it appears full screen instead of the popup.

**Pull request merged**
